// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

module.exports = {
  webpackDevPort: webpackDevPort,
  resolve: {
    extensions: ['', '.js']
  },
  entry: {
    index: path.resolve(__dirname, './public/js/main.js'),
  },
  output: {
    path: path.resolve(__dirname, './public/js/dist/'),
    publicPath: "http://localhost:" + webpackDevPort + "/public/js/dist",
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test: /\.ejs$/,
        loader: 'ejs-loader?variable=data'
      }
    ]
  },
  devtool: 'source-map'
};

//# sourceMappingURL=webpack.config.js.map
