// Generated by CoffeeScript 1.8.0
"use strict"

var fs = require('fs');

var path = require('path');

var express = require('express');

var router = express.Router();

var controllerDirName = './controller';

var controllerDir = path.resolve(__dirname, controllerDirName);

var jsFileRegExp = /\.js$/;

var loadAllRoutes = function (dir) {
  fs.readdirSync(dir).filter(function (controllerName) {
    return jsFileRegExp.test(controllerName);
  }).forEach(function (controllerName) {
    var controller,fn, route, routerName;
    controllerName = controllerName.replace(/\.js$/, '');
    try {
      controller = require(path.resolve(__dirname, dir, controllerName));
      for (routerName in controller) {
        fn = controller[routerName];
        route = "/" + controllerName + "/" + routerName;

        [].concat(fn).forEach(function(f){
          router.get(route, f);
        });
      }
    } catch (_error) {
      return console.log(_error);
    }
  });
};

[controllerDir].forEach(loadAllRoutes);

module.exports = router;


//# sourceMappingURL=index.js.map
