// Generated by CoffeeScript 1.8.0
"use strict"

var fs = require('fs');

var path = require('path');

var express = require('express');

var router = express.Router();

var apiDirName = './api';

var apiDir = path.resolve(__dirname, apiDirName);

var controllerDirName = './controller';

var controllerDir = path.resolve(__dirname, controllerDirName);

var jsFileRegExp = /\.js$/;

var loadAllRoutes = function (dir) {
  fs.readdirSync(dir).filter(function (controllerName) {
    return jsFileRegExp.test(controllerName);
  }).forEach(function (controllerName) {
    var controller, e, fn, route, routerName, _results;
    controllerName = controllerName.replace(/\.js$/, '');
    try {
      controller = require(path.resolve(__dirname, dir, controllerName));
      _results = [];
      for (routerName in controller) {
        fn = controller[routerName];
        route = "/" + controllerName + "/" + routerName;
        _results.push(router.get(route, fn));
      }
      return _results;
    } catch (_error) {
      e = _error;
      return console.log(e);
    }
  });
};

[apiDir, controllerDir].forEach(loadAllRoutes);

module.exports = router;


//# sourceMappingURL=index.js.map
