// Generated by CoffeeScript 1.8.0
(function() {
  var apiDir, apiDirName, controllerDir, controllerDirName, express, fs, jsFileRegExp, loadAllRoutes, path, router;

  fs = require('fs');

  path = require('path');

  express = require('express');

  router = express.Router();

  apiDirName = './api';

  apiDir = path.resolve(__dirname, apiDirName);

  controllerDirName = './controller';

  controllerDir = path.resolve(__dirname, controllerDirName);

  jsFileRegExp = /\.js$/;

  loadAllRoutes = function(dir) {
    return fs.readdirSync(dir).filter(function(controllerName) {
      return jsFileRegExp.test(controllerName);
    }).forEach(function(controllerName) {
      var controller, e, fn, route, routerName, _results;
      controllerName = controllerName.replace(/\.js$/, '');
      try {
        controller = require(path.resolve(__dirname, dir, controllerName));
        _results = [];
        for (routerName in controller) {
          fn = controller[routerName];
          route = "/" + controllerName + "/" + routerName;
          _results.push(router.get(route, fn));
        }
        return _results;
      } catch (_error) {
        e = _error;
        return console.log(e);
      }
    });
  };

  [apiDir, controllerDir].forEach(loadAllRoutes);

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
