// Generated by CoffeeScript 1.8.0
var path = require('path');

var allowAll = process.env.NODE_ENV ? process.env.NODE_ENV === 'development' : true;

var wxReg = /micromessenger/;

module.exports = function (req, res, next) {
  var isTest = req.query.isTest === 'true';
  var userAgent = req.headers['user-agent'];

  var iswx = wxReg.test(userAgent.toLowerCase());

  console.log(iswx , isTest , allowAll);

  if (iswx || isTest || allowAll) {
    return next();
  } else {
    return res.render('error/wxForbidden');
  }
};

//# sourceMappingURL=fromWX.js.map
