// Generated by CoffeeScript 1.8.0
(function() {
  var MongoClient, connectTo, connectedDb, url;

  MongoClient = require('mongodb').MongoClient;

  url = 'mongodb://localhost:27017/sails';

  connectedDb = null;

  connectTo = function() {
    return new Promise(function(resolve) {
      return MongoClient.connect(url, function(err, db) {
        if (err) {
          throw err;
        }
        return resolve(db);
      });
    });
  };

  module.exports = {
    db: function(cb) {
      if (connectedDb) {
        return cb(connectedDb);
      } else {
        return connectTo().then(function(db) {
          connectedDb = db;
          return cb(connectedDb);
        });
      }
    }
  };

}).call(this);

//# sourceMappingURL=model.js.map
